### ISSUE TITLE
Build warnings and test failure with clang/clang++ 10

### ISSUE THREAD

**Issue by stanman29** [dspinellis/cscout#71]
Hi there,
I am trying to build and test cscout and I have no idea if I am doing it correctly. 
I just set $CC = /usr/bin/clang and $CXX = /usr/bin/clang++ (version 10) Ubuntu 20.04 LTS
And used my normal make line to output stdout to a file.
eg: 
1st logfile: make  -j6 -i 2>&1 | tee -a clang-cscout-build-op-20200811.log
2nd logfile: make test -j6 -i  2>&1 | tee -a clang-cscout-build-optests-20200811.log

Here are the logfiles:
[clang-cscout-build-op.zip](https://github.com/dspinellis/cscout/files/5054914/clang-cscout-build-op.zip)

I installed cscout to home/user/mystuff/programs but get this error when I try to use csmake on my project.

../../programs/bin/csmake -j6 2>&1 | tee -a clang-build-op-20200801.log
Unable to open /tmp/spy-make.33214//usr/bin/clang for writing: No such file or directory

Thanks for any advice on correctly build cscout,
Regards, 
         David.

**Comment by dspinellis** [comment]
Build seems to be correct.  The tests fail, because the `CC` and `CXX` variables have an absolute path.  If you can set them to `clang` and `clang++` it should work.  Using absolute paths won't currently work (and will be tricky to fix), because the *csmake* program substitutes the executables in the `PATH` with a shim.
